- name: Primer play
  hosts: 192.168.0.100
  become: true
  remote_user: centos
  tasks:
    - name: Configurando Ambiente
    - include: grupos.yml
    - include: usuarios.yml
    - include: disco.yml
    - include: paquetes.yml
    
